### ISSUE TITLE
The readme doesn't explain what the notebook in this repo does. 

### ISSUE THREAD

**Issue by dustyny** [XmYx/stable-diffusion-gradio-anim-opt#1]

**Comment by dustyny** [comment]
I think more people would check out your notebook if you explained what it does and showed some screenshots. I'd also put a link to the CoLab in so they can quickly launch it without having to look for the link.

**Comment by XmYx** [comment]
Hi there!

I'm glad that you have found one of our early trials : )
Please do join our discord to find out where the latest repo is, we currently have a Streamlit version with nodes, and a WIP PyQt6 version, already running on Windows, Linux and macOS (3s / it on m1 macbook pro gen1).
https://discord.gg/4Y9jDFS9

This repo will not be maintained, and Streamlit version remains a playground for ideas, but focus is on the standalone version. Also, Google Colab is not actively supported as they have made the service less viable.

Thanks,
Miklos

**Comment by dustyny** [comment]
Thanks for the update.. Can you mark this repo as depreciated so others who find it will know not to spend time trying to figure it out?

**Comment by XmYx** [comment]
There is a repo specifically for Colab which I have made and used before. There are over 4000 forks for Stable Diffusion as I'm writing these lines, 99% of them are not documented, and have no addition at all. I think you're getting my point. : ))
